---
language: ruby

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec strings:generate reference'

matrix:
  fast_finish: true
  include:
  - rvm: 2.4.9
    env: PUPPET_GEM_VERSION="~> 5"
    bundler_args: --without system_tests development
  - rvm: 2.4.9
    env: PUPPET_GEM_VERSION="~> 5" FIXTURES_YML=".fixtures-latest.yml"
    bundler_args: --without system_tests development
  - rvm: 2.5.7
    env: PUPPET_GEM_VERSION="~> 6"
    bundler_args: --without system_tests development
  - rvm: 2.5.7
    env: PUPPET_GEM_VERSION="~> 6" FIXTURES_YML=".fixtures-latest.yml"
    bundler_args: --without system_tests development
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet5
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet6
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet5
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet6
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="debian-8" BEAKER_PUPPET_COLLECTION=puppet5
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="debian-8" BEAKER_PUPPET_COLLECTION=puppet6
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="debian-9" BEAKER_PUPPET_COLLECTION=puppet5
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="debian-9" BEAKER_PUPPET_COLLECTION=puppet6
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1604" BEAKER_PUPPET_COLLECTION=puppet5
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1604" BEAKER_PUPPET_COLLECTION=puppet6
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet5
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet6
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="amazonlinux-201803" BEAKER_PUPPET_COLLECTION=puppet5
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="amazonlinux-201803" BEAKER_PUPPET_COLLECTION=puppet6
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="amazonlinux-2" BEAKER_PUPPET_COLLECTION=puppet5
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="amazonlinux-2" BEAKER_PUPPET_COLLECTION=puppet6
    script: bundle exec rake beaker
allow_failures:
  - rvm: 2.4.9
    env: PUPPET_GEM_VERSION="~> 5" FIXTURES_YML=".fixtures-latest.yml"
  - rvm: 2.5.7
    env: PUPPET_GEM_VERSION="~> 6" FIXTURES_YML=".fixtures-latest.yml"
branches:
  only:
    - master
    - /^v\d/

notifications:
  email: false
  slack:
    rooms:
      - secure: R1ThBe5UcmcX5UqnMAWEl5e0JpO1MjsCJDvsDfgTZQ7Nb7gYzj6T9lls11HxxoALffkdMbi7g7qlrwQ9ajblIZlS27aMbucwaMbWt6uiepVITHTub6+ZhM1yAcgFgRk2HsfaZnaB0LERW4SIfTTe/hGFIMgHGDYSf+NYqM3ikhY=
    on_success: change
    on_failure: always
